name: Validate PR

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Vet
        run: |
          go vet

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout 5m

      - name: Test w/ Coverage
        run: |
          go test -race -v \
            -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Build Coverage Report
        run: |
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
          gocov convert cover.out | gocov-xml > coverage.cobertura.xml

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml
          format: markdown
          fail_below_min: false
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "50 75"

      - name: Add Code Coverage Comment to PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: code-coverage-results.md
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: coverage-summary
